/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karina.gui;

import java.text.SimpleDateFormat;
import com.karina.library.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class MainTransaksi extends javax.swing.JFrame {

    private int id = 0;//variable id untuk id Transaksi
    private String code;//variable code untuk Transaksi kode
    private DefaultComboBoxModel cbModel;//Jcombobox model
    private DefaultTableModel tbModel;//Jtable model
    private ArrayList<Item> belanja = new ArrayList<>();//variabel pembelanjaan untuk menampilkan transaksi item
    
   //konstruktor
    public MainTransaksi() {
        ComboTransaksi comboTransaksi = new ComboTransaksi();
        this.cbModel = new DefaultComboBoxModel<>(comboTransaksi.getNama().toArray());
        TableTransaksi tableTransaksi = new TableTransaksi();
        this.tbModel = new DefaultTableModel(tableTransaksi.getColumnNama(), 0);
        initComponents();
    }
    
     //untuk penambahan id
    private void incId(){
        this.id += 1;
    }
    //untuk pengurangan id
    private void decId(){
        this.id -= 1;
    }
    //set fungsi code
    private String setCode(){
        this.incId();
        //untuk pemformatan tanggal
        String st = new SimpleDateFormat("yyMMdd").format(new Date());
        this.code = String.format(st+"%02d", this.id);
        return code;
    }
    //untuk menyimpan item yang dipilih yaitu nama, harga, dan jumlah
    private Object[] addItem (String nama , int jumlah) {
        float harga = 0 ;
        ComboTransaksi items = new ComboTransaksi () ;
        for (int i = 0; i < items.getNama().size(); i++) {
            if (nama.equalsIgnoreCase(items.getNama().get(i))) {
                harga = items.getHarga().get(i) ;
            }
        }
        Object[] obj = {
            nama ,
            harga ,
            jumlah ,
        } ;
        return obj ;
    }
    //mengupdate fungsi jumlah yang diinginkan
    private void updateJumlah (String nama , int add) {
        ArrayList<String> item = new ArrayList<> () ;
        for (int i = 0; i < tbModel.getRowCount(); i++) {
            item.add (tbModel.getValueAt (i , 0).toString()) ;
        }
        for (int i = 0; i < item.size(); i++) {
            if (item.get(i).equals(nama)) {
                int jumlah = new Integer (tbModel.getValueAt (i , 2).toString()) ;
                tbModel.setValueAt (jumlah+add , i , 2) ;
            }
        }
    }
    //mengecek apakah ada item double yang terpilih pada item sebelumnya yang sudah dipilih
    private boolean isDuplicate (String nama) {
        boolean result = false ;
        ArrayList <String> item = new ArrayList<>() ;
        for (int i = 0; i < tbModel.getRowCount(); i++) {
            item.add (tbModel.getValueAt(i, 0).toString()) ;
        }
        for (String i : item) {
            if (i.equals(nama)) {
                result = true ;
            }
        }
        return result ;
    }
    //mengecek jika terdapat isi tabel kosong
    private boolean isEmpty() {
        return this.transaksiTable.getModel().getRowCount() <= 0 ;
    }
    //mendisable tombol remove dan save jika terdapet isi tabel kosong yang tidak dipilih
    private void belanja() {
        if (isEmpty()) {
            this.saveButton.setEnabled(false) ;
            this.removeButton.setEnabled(false) ;
        } else {
            this.saveButton.setEnabled(true) ;
            this.removeButton.setEnabled(true) ;
        }
    }
    //melakukan transaksi baru jika sudah menyelesaikan transaksi sebelumnya
    private void newTransaksi () {
        this.jumlahText.setText(" ") ;
        this.codeText.setText(" ") ;
        this.newButton.setEnabled(true) ;
        this.saveButton.setEnabled(false) ;
        this.cancelButton.setEnabled(false) ;
        this.addButton.setEnabled(false) ;
        this.removeButton.setEnabled(false) ;
        this.removeButton.setEnabled(false) ;
        this.jumlahText.setEnabled(false) ;
        this.itemsComboBox.setEnabled(false) ;
        this.tbModel.setRowCount(0) ;
        this.belanja.clear() ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeLabel = new javax.swing.JLabel();
        itemsLabel = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        itemsComboBox = new javax.swing.JComboBox<>();
        jumlahText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();
        newButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codeLabel.setText("Code");

        itemsLabel.setText("Items");

        codeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTextActionPerformed(evt);
            }
        });

        itemsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Gula" }));
        itemsComboBox.setSelectedIndex(-1);
        itemsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsComboBoxActionPerformed(evt);
            }
        });

        jumlahText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahTextActionPerformed(evt);
            }
        });

        transaksiTable.setModel(this.tbModel);
        jScrollPane1.setViewportView(transaksiTable);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel)
                    .addComponent(itemsLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(41, 41, 41)
                                .addComponent(cancelButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jumlahText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemsLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton)
                        .addComponent(jumlahText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            //looping untuk setiap tabel
            for (int i = 0; i < tbModel.getRowCount(); i++) {
                // menyimpan nama item dan jumlah item menjadi variable
                String nama = tbModel.getValueAt (i , 0).toString () ;
                float harga = new Float (tbModel.getValueAt(i , 1).toString()) ;
                int jumlah = new Integer (tbModel.getValueAt (i , 2).toString()) ;
                this.belanja.add (new Item(nama , harga , jumlah)) ;   
            }
            //instansiasi kelas Transaksi dengan kode dan menjalankan penyimpanan belanja
            Transaksi tsk = new Transaksi (this.code , this.belanja) ;
            //Stringbuilder untuk menangani output Transaksi
            StringBuilder sbr = new StringBuilder() ;
            //menambahkan hasil transaksi
            sbr.append(tsk.printDetail()) ;
            //memanggil dialog dengan StringBuilder
            JOptionPane.showMessageDialog(this , sbr , "Transaksi" , JOptionPane.INFORMATION_MESSAGE) ;
            //digunakan untuk melakukan transaksi baru
            newTransaksi () ;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        newTransaksi() ;
        this.decId() ;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jumlahTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahTextActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //mengecek apakah ada baris yang dipilih
        if (transaksiTable.getSelectedRow() <0) {
            //apabila tidak ada , maka akan muncul tulisan 
            String sbr = "Pilihlah item yang akan dihapus" ;
            JOptionPane.showMessageDialog(this , sbr , "Information" , JOptionPane.INFORMATION_MESSAGE) ;  
        } else {
            //apabila ada baris yg dipilih , maka baris tersebut akan dihapus
            int count = transaksiTable.getSelectedRows().length ;
            for (int i = 0; i < count; i++) {
                tbModel.removeRow(transaksiTable.getSelectedRow()) ;
            }
            
        }
        this.belanja() ;
    }//GEN-LAST:event_removeButtonActionPerformed

    private void itemsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsComboBoxActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        this.jumlahText.setText ("1") ;
        this.newButton.setEnabled (false) ;
        this.cancelButton.setEnabled (true) ;
        this.addButton.setEnabled (true) ;
        this.jumlahText.setEnabled (true) ;
        this.itemsComboBox.setEnabled (true) ;
        this.codeText.setText (this.setCode()) ;
    }//GEN-LAST:event_newButtonActionPerformed

    private void codeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //mendapatkan item yang telah dipilih
        String nama = this.itemsComboBox.getSelectedItem().toString() ;
        //jumlahText disetting sebagai Integer
        int jumlah = new Integer (this.jumlahText.getText()) ;
        //mengecek apakah suatu barang ada yang double atau tidak
        if (isDuplicate(nama)) {
            updateJumlah (nama , jumlah) ;
        } else {
            tbModel.addRow(addItem(nama , jumlah));
        }
        this.belanja () ;
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeText;
    private javax.swing.JComboBox<String> itemsComboBox;
    private javax.swing.JLabel itemsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahText;
    private javax.swing.JButton newButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable transaksiTable;
    // End of variables declaration//GEN-END:variables
}
